[project]
name = 'Decentralized-Financial-Technology-Alternative-Credit-Scoring'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.data-provider-verification]
path = 'contracts/data-provider-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.privacy-protection]
path = 'contracts/privacy-protection.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
